/**
 * SlidFinance
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CategoryDistribution } from './categoryDistribution';


export interface GeneratedRule { 
    accountId?: number;
    description?: string;
    mcc?: number;
    bankCategory?: string;
    categories?: Array<CategoryDistribution>;
    count?: number;
}
