/**
 * SlidFinance
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Mcc } from './mcc';


export interface Merchant { 
    id?: number;
    address?: string;
    mccId: number;
    mcc: Mcc;
    name: string;
    displayName?: string;
    created: Date;
    updated?: Date;
}
