/**
 * SlidFinance
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ProductType } from './productType';


export interface Product { 
    id?: number;
    title?: string;
    bankId?: number;
    type?: ProductType;
    image?: string;
    isPublic?: boolean;
    approved?: boolean;
}
