/**
 * SlidFinance
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export type ProductType = 'SavedAccount' | 'Card' | 'Deposit';

export const ProductType = {
    SavedAccount: 'SavedAccount' as ProductType,
    Card: 'Card' as ProductType,
    Deposit: 'Deposit' as ProductType
};
